server.port=${SERVER_PORT:8085}
spring.application.name=auth-service

spring.datasource.url=${PRODUCT_DB_URL:jdbc:postgresql://${RDS_HOST}:${DB_PORT:5432}/ecommerce_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.url=${spring.datasource.url}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://discovery-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

security.jwt.secret=${JWT_SECRET}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
