server.port=${SERVER_PORT:8085}
spring.application.name=auth-service

spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://${RDS_HOST}:${DB_PORT:5432}/auth_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASS}}
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${SPRING_LIQUIBASE_USER:${SPRING_DATASOURCE_USERNAME:${DB_USER}}}
spring.liquibase.password=${SPRING_LIQUIBASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:${DB_PASS}}}

eureka.client.service-url.defaultZone=http://172.31.18.159:8761/eureka/
eureka.instance.prefer-ip-address=true

security.jwt.secret=${JWT_SECRET}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
