server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:lb://auth-service}
          predicates:
            - Path=/auth/**,/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:lb://product-service}
          predicates:
            - Path=/products,/products/**,/api/v1/products,/api/v1/products/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: cart-service
          uri: ${CART_SERVICE_URL:lb://cart-service}
          predicates:
            - Path=/carts,/carts/**,/api/v1/carts/**,/api/v1/carts
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: order-service
          uri: ${ORDER_SERVICE_URL:lb://order-service}
          predicates:
            - Path=/orders,/orders/**,/api/v1/orders/**,/api/v1/orders
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:lb://payment-service}
          predicates:
            - Path=/payments,/payments/**,/api/v1/payments/**,/api/v1/payments
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: seller-service
          uri: ${SELLER_SERVICE_URL:lb://seller-service}
          predicates:
            - Path=/sellers/**,/api/v1/sellers/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
        - id: campaign-service
          uri: ${CAMPAIGN_SERVICE_URL:lb://campaign-service}
          predicates:
            - Path=/campaigns/**,/api/v1/campaigns/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

security:
  jwt:
    secret: ThisIsA32CharLongGatewayJwtSecret!
