server.port=${SERVER_PORT:8080}
spring.application.name=api-gateway

spring.cloud.gateway.default-filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:lb://auth-service}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/api/v1/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/v1/(?<segment>.*),/$\{segment}

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=${PRODUCT_SERVICE_URL:lb://product-service}
spring.cloud.gateway.routes[1].predicates[0]=Path=/products,/products/**,/api/v1/products,/api/v1/products/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/v1/(?<segment>.*),/$\{segment}

spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=${CART_SERVICE_URL:lb://cart-service}
spring.cloud.gateway.routes[2].predicates[0]=Path=/carts,/carts/**,/api/v1/carts/**,/api/v1/carts
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/v1/(?<segment>.*),/$\{segment}

spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=${ORDER_SERVICE_URL:lb://order-service}
spring.cloud.gateway.routes[3].predicates[0]=Path=/orders,/orders/**,/api/v1/orders/**,/api/v1/orders
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/api/v1/(?<segment>.*),/$\{segment}

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=${PAYMENT_SERVICE_URL:lb://payment-service}
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments,/payments/**,/api/v1/payments/**,/api/v1/payments
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/api/v1/(?<segment>.*),/$\{segment}

spring.cloud.gateway.routes[5].id=seller-service
spring.cloud.gateway.routes[5].uri=${SELLER_SERVICE_URL:lb://seller-service}
spring.cloud.gateway.routes[5].predicates[0]=Path=/sellers/**,/api/v1/sellers/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/api/v1/(?<segment>.*),/$\{segment}

spring.cloud.gateway.routes[6].id=campaign-service
spring.cloud.gateway.routes[6].uri=${CAMPAIGN_SERVICE_URL:lb://campaign-service}
spring.cloud.gateway.routes[6].predicates[0]=Path=/campaigns/**,/api/v1/campaigns/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/api/v1/(?<segment>.*),/$\{segment}

eureka.client.service-url.defaultZone=http://172.31.18.159:8761/eureka/

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=${JWT_SECRET}
