server.port=${SERVER_PORT:8080}
spring.application.name=api-gateway

spring.cloud.gateway.default-filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://auth-service:8085}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=${PRODUCT_SERVICE_URL:http://product-service:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=${CART_SERVICE_URL:http://cart-service:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/carts,/carts/**

spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=${ORDER_SERVICE_URL:http://order-service:8083}
spring.cloud.gateway.routes[3].predicates[0]=Path=/orders,/orders/**

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=${PAYMENT_SERVICE_URL:http://payment-service:8084}
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments,/payments/**

spring.cloud.gateway.routes[5].id=seller-service
spring.cloud.gateway.routes[5].uri=${SELLER_SERVICE_URL:http://seller-service:8086}
spring.cloud.gateway.routes[5].predicates[0]=Path=/sellers/**

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://discovery-server:8761/eureka/}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=${JWT_SECRET}
