spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://localhost:5435/payment_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

iyzico.base-url=${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}
iyzico.api-key=${IYZICO_API_KEY:}
iyzico.secret-key=${IYZICO_SECRET_KEY:}
payment.iyzipay.require-real=${PAYMENT_IYZIPAY_REQUIRE_REAL:false}
