server.port=${SERVER_PORT:8761}
spring.application.name=discovery-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://discovery-server:8761/eureka/}
