server.port=${SERVER_PORT:8082}
spring.application.name=cart-service

spring.datasource.url=${CART_DB_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:cart_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASS}}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${SPRING_LIQUIBASE_USER:${SPRING_DATASOURCE_USERNAME:${DB_USER}}}
spring.liquibase.password=${SPRING_LIQUIBASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:${DB_PASS}}}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://discovery-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
